import java.util.ArrayList;

public class Airport
{
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights)
    {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights()
    {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue()
    {
        double revenue= 0.0;
        for (Flight newFlight : allFlights)
        {
            if (newFlight.getNumPassengers() > newFlight.getCapacity())
            {
                revenue += newFlight.getPrice() * newFlight.getCapacity();
            }
            else
            {
                revenue += newFlight.getPrice() * newFlight.getNumPassengers();
            }
        }
        return revenue;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights()
    {
        int passengers = 0;
        for (int i = allFlights.size(); i >= 0; i--)
        {
            Flight currentFlight = allFlights.get(i);
            int minimum = (int) (currentFlight.getCapacity() * 0.2);
            int newPassengers = currentFlight.getNumPassengers();
            if (newPassengers < minimum)
            {
                passengers += newPassengers;
                allFlights.remove(i);
            }
        }
        return passengers;
    }
}